zabbixServer:
  enabled: true
  service:
    type: NodePort
    nodePort: 30051

zabbixWeb:
  enabled: true
  service:
    type: NodePort
    nodePort: 30052

zabbixAgent:
  enabled: true
  daemonset:
    enabled: true

postgresql:
  enabled: true

mariadb:
  enabled: false

ingress:
  enabled: false
