apiVersion: v1
kind: Service
metadata:
  name: yolov5-service
spec:
  selector:
    app: yolov5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Only use if your container serves HTTP logs/metrics
