---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: yolvo
    meta.helm.sh/release-namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-db-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: yolvo
    meta.helm.sh/release-namespace: default
type: Opaque
stringData:
  username: zabbix
  password: zabbix123

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/zabbix-db"
  claimRef:
    namespace: monitoring
    name: zabbix-storage-zabbix-postgresql-0



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi




---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-postgresql
  namespace: monitoring
  labels:
    app: zabbix-postgresql
spec:
  serviceName: "zabbix-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-postgresql
  template:
    metadata:
      labels:
        app: zabbix-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: zabbix
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: password
          volumeMounts:
            - name: zabbix-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: zabbix-storage
        labels:
          app: zabbix-postgresql
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgresql
  namespace: monitoring
  labels:
    app: zabbix-postgresql
spec:
  ports:
    - port: 5432
  selector:
    app: zabbix-postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: monitoring
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgresql.monitoring.svc.cluster.local
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: password
          ports:
            - containerPort: 10051
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: monitoring
  labels:
    app: zabbix-server
spec:
  selector:
    app: zabbix-server
  ports:
    - port: 10051
      targetPort: 10051
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: monitoring
  labels:
    app: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgresql.monitoring.svc.cluster.local
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zabbix-db-secret
                  key: password
            - name: ZBX_SERVER_HOST
              value: zabbix-server.monitoring.svc.cluster.local
            - name: PHP_TZ
              value: "UTC"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: monitoring
  labels:
    app: zabbix-web
spec:
  type: NodePort
  selector:
    app: zabbix-web
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30052
