apiVersion: v1
kind: Service
metadata:
  name: zabbix-service
spec:
  type: NodePort
  selector:
    app: yolov5
  ports:
    - name: yolvo-http
      protocol: TCP
      port: 10050
      targetPort: 10050
      nodePort: 30080
