---
releases:
  - name: yolvo
    chart: ./yolvo
    installed: true
    values:
      - ./yolvo/values.yaml

  - name: zabbix
    chart: zabbix-community/zabbix
    installed: true
    values:
      - ./yolvo/zabbix-values.yaml
